#!/usr/bin/perl
#
# bsidessf17 - dnscap
#
# script de analisis inicial
#
# fusion_ordenado.txt tiene el formato: <paquete>\t<datos>
#
# Rev.20170212 by sn4fu

use strict;
use warnings;
use 5.016;

my $fichero = 'fusion_ordenado.txt';
open(my $fh,$fichero)
or die "No se ha encontrado el fichero '$fichero' $!";

while (my $linea = <$fh>) {
 chomp $linea;						# quitar CR
 my ($paquete, $datos) = split /\t/, $linea;		# parsear usando TAB como separador
 print "$paquete\n";					# imprimir numero de paquete
 print "$datos\n";					# imprimir datos del paquete
 my @cadenas = split /\./, $datos;			# parsear las partes de la cadena de datos separadas con '.'
 my $cadena_sobrante1 = 'org';				# las cadenas 'org' no nos interesan
 @cadenas = grep {!/$cadena_sobrante1/} @cadenas;
 my $cadena_sobrante2 = 'skullseclabs';			# las cadenas 'skullseclabs' no no sinteresan
 @cadenas = grep {!/$cadena_sobrante2/} @cadenas;
 foreach (@cadenas)
   {
      print "$_\n";					# imprimir la cadena HEX
      say (pack "H*",$_);				# traducir la cadena a ASCII
   }
}
